# Generated by Django 3.2.21 on 2023-09-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_number_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='number_stars',
            new_name='stars',
        ),
    ]
